project_id = "xxikcvtphdixcfxrwvzs"

[functions.rd-marketing-webhook]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false

[functions.tv-dashboard]
verify_jwt = false

[functions.tv-dashboard-public]
verify_jwt = false
